# Generated by Django 4.0.3 on 2022-03-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=255)),
                ('post_image', models.ImageField(upload_to='')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_type', models.CharField(max_length=255)),
                ('post_content', models.TextField()),
            ],
        ),
    ]
